### ISSUE TITLE
Extension not renaming Snowflake Resultset Tabs

### ISSUE THREAD

**Issue by kevinSpezia** [Luke-Callaghan23/VSCode-Tab-Labels#4]
VS Code version 1.95.2
Snowflake extension version 1.10.5
Rename Tabs version 0.0.2

The display text of Snowflake resultsets is different from what shows up when first attempting to rename the tab. Example:
Tab name when renaming (after right-click > Rename Tab): **webview-da1a17ad-e710-42d4-85d6-cca1356fe31f**
Tab name displayed in VS code: **Results: 01b86508-0c07-fb0c-0002-f0a6699794fe**

After renaming the tab using this extension, the tab's name still displays **Results: 01b86508-0c07-fb0c-0002-f0a6699794fe**. When I go back into the Rename Tab dialog, my new tab name is saved there.

Before:
![image](https://github.com/user-attachments/assets/77c2b30b-ac42-48ab-8025-d6d74bea005d)
After:
![image](https://github.com/user-attachments/assets/a962b388-126d-45be-b8fe-be361fe4de71)

**Comment by kevinSpezia** [comment]
Note that it's working for me on other tab types - it's just these Snowflake results that aren't renaming.

**Comment by Luke-Callaghan23** [comment]
Hi @kevinSpezia I don't know much about Snowflake, but it seems that the result set of snowflake uses a custom webview to display their data.  This is important because VS Code provides no APIs for other extensions or users to rename the tabs of a webview.  Webview tab names are managed within the webview's extension itself and cannot be accessed outside of that.  I would recommend trying to create a ticket like this with the Snowflake extension authors.

Again, I don't know much about Snowflake so I may be missing something.  The result set that snowflake is displaying, is it based of a file that was generated on disk?  If so, you can try renaming that file (not through rename-tabs extension, but renaming the file on the file system), and maybe then the webview will show a better name.  Not sure.

**Comment by kevinSpezia** [comment]
Awesome, thanks for the information!

Snowflake runs entirely on cloud so the result set isn't located on local disk, though it's generated based on a SQL script that is local.

I'll open a ticket with them about this - it would be really nice to be able to have those results named something that's actually usable. In the meantime, I'll close this. Appreciate the extension, and the quick response!
